Hotfix/38 refatorar comunicacao com a api
fga-eps-mds/2023.2-Dnit-Front pull request #20
Opened 2023-11-03 22:57 UTC by victorhugo21

## _Issue :_ [#38](https://github.com/fga-eps-mds/2023.2-Dnit-DOC/issues/38)

## Descrição
Foi feita a refatoração de todas os arquivos de requisição para a api na pasta service, organizando de uma forma melhor e mais adequada ao nosso projeto.
## Imagens:
![image](https://github.com/fga-eps-mds/2023.2-Dnit-Front/assets/54643372/4a14bf96-78de-4655-9ba1-1d922b829792)
![image](https://github.com/fga-eps-mds/2023.2-Dnit-Front/assets/54643372/ec105b17-e238-48e5-8f79-b58afb6d6f56)
![image](https://github.com/fga-eps-mds/2023.2-Dnit-Front/assets/54643372/0f3b2f26-b834-4f84-928a-22277ece560d)

## Tipo de alterações

- [ ] Separação dos arquivos das requisições por serviço
- [ ] Adição do arquivo apiUtils para evitar a repetição de código nas requisições

## Lista de controle:

- [ ] Atribui este pull request ao projeto
- [ ] Meu código segue a folha de estilos implementada
- [ ] Meus _commits_ seguem a política de commits do projeto.
- [ ] Todos os testes foram aprovados.

2023-11-07 00:38 UTC, RafaelBP02 reviewed
- Rodei localmente o frontend e não detectei erros que chamaram minha atenção
- Encontrei um erro de português (fiz uma sugestão para corrigir)
- O teste "Testes para o componente EditarTipoPerfilDialog › Deve confirmar o tipo do Perfil corretamente" falhou.
- Eu recomendo executar novamente todos os testes na sua máquina visto que você alterou bastante as requisições para o back.

2023-11-07 21:48 UTC, VitorLamego commented on src/components/PerfilDialog/index.tsx
> +import {fetchAtualizaPerfil} from "../../service/usuarioApi";
Dá pra colocar esses três imports na mesma linha

2023-11-07 21:48 UTC, VitorLamego commented on src/components/cadastrarEscolas/cadastroManual/FormularioCadastro.tsx
> +import {fetchMunicipio} from "../../../service/escolaApi";
Mesma coisa dos imports aqui, são todos do mesmo arquivo

2023-11-07 21:54 UTC, VitorLamego commented on src/components/cadastrarSinistros/UploadPlanilhaSinistros.tsx
> +        const response = await fetchCadastraSinistro(formData);
response foi declarado, mas não é utilizado

2023-11-07 21:55 UTC, VitorLamego commented on src/components/escolasCadastradas/FiltragemTabela.tsx
> +import {fetchMunicipio} from "../../service/escolaApi";
Nesse arquivo também tem os imports do mesmo arquivo, verificar nos arquivos alterados outros locais que também tenham isso.

2023-11-07 21:58 UTC, VitorLamego commented on src/service/apiUtils.ts
> +export async function fetchCadastros<T>(url: string, data: T): Promise<ResponseStatus> {
Achei estranho a utilização do método com o nome "fetch" e sendo feito uma request POST para o servidor. "Fetch" dá uma ideia de busca, esse nome passa a ideia de que está retornando todos os cadastros existentes.

2023-11-07 21:58 UTC, VitorLamego commented on src/service/apiUtils.ts
> +export async function fetchModificador<T>(url: string, data: T): Promise<ResponseStatus>{
Mesma coisa do fetch do comentário anterior.

2023-11-07 21:59 UTC, VitorLamego commented on src/service/usuarioApi.ts
> +    //return fetchCadastros<PerfilModel>(URL.cadastrarPerfilUrl, perfil);
remover comentário.

2023-11-07 22:00 UTC, VitorLamego commented on src/service/usuarioApi.ts
Ver a questão da nomenclatura com "fetch" também.

2023-11-07 22:04 UTC, VitorLamego requested changes
Bom trabalho, acredito que tenha ficado muito melhor com essa estruturação. Os testes estão ok para mim. Tirando o que já foi comentado em outras revisões, deixei alguns comentários referente a nomenclatura e código não utilizado, mas acredito que sejam só detalhes.

2023-11-08 00:17 UTC, VitorLamego approved these changes
Bom trabalho!

2023-11-08 01:27 UTC, RafaelBP02 approved these changes
Não encontrei um novo problema. O Vitor Lamego fez boas observações também

2023-11-08 13:48 UTC, merged