Feat/ajustes us2 gerenciar usuarios
fga-eps-mds/2023.2-Dnit-Front pull request #22
Opened 2023-11-11 05:38 UTC by RafaelBP02

## _Issue :_ [Melhoria] Usabilidade e edição de uf e municipios

Resolves fga-eps-mds/2023.1-Dnit-Front#103

 

## Descrição
Melhoria da usabilidade dos dropdowns e das modais. Além disso, adiciona a funcionalidade de Editar a UF e municipio de um usuário

## Tipo de alterações

- [ ] _correção_ _de_ _bug_
- [ ] Nova _feature_
- [ ] Outro: 
## Lista de controle:

- [ ] Atribui este pull request ao projeto
- [ ] Meu código segue a folha de estilos implementada
- [ ] Meus _commits_ seguem a política de commits do projeto.
- [ ] Minhas alterações requerem modificações na documentação atual.
- [ ] Atualizei a Documentação
- [ ] Adicionei testes para cobrir minhas alterações.
- [ ] Todos os testes foram aprovados.

2023-11-11 05:40 UTC, RafaelBP02 commented
Vou corrigir esses conflitos quando o PR#101(correção da paginação) for resolvido

2023-11-13 00:11 UTC, VitorLamego commented on src/tests/stub/usuarioModelos.ts
> +    municipio: null, //necessario para o teste de carregar um usuario sem municipio
Esse null está quebrando o docker, esse tipo não pode receber este valor.

2023-11-13 00:58 UTC, VitorLamego requested changes
Ao abrir a parte de "Gerenciar Usuário" é mostrado esse erro.

<img width="799" alt="Captura de Tela 2023-11-12 às 21 57 22" src="https://github.com/fga-eps-mds/2023.2-Dnit-Front/assets/54643464/26771fbc-abbe-4411-8ece-fff7e590b12a">

2023-11-13 02:28 UTC, DanielPortods reviewed
Acredito que essas alterações são necessárias

2023-11-13 02:28 UTC, DanielPortods commented on src/models/usuario.ts
> +    municipio: MunicipioData;
```suggestion
    municipio?: MunicipioData;
```

2023-11-13 02:28 UTC, DanielPortods commented on src/pages/gerencia/GerenciarUsuario/index.tsx
> +  }
```suggestion
  function procuraRotuloMunicipio(usuario: UsuarioModel) {
         return usuario.municipio === null ? "Não Cadastrado" : usuario.municipio?.nome;
  }
```

2023-11-13 02:28 UTC, DanielPortods commented on src/pages/gerencia/GerenciarUsuario/index.tsx
> +              '2': `${procuraRotuloUf(usuario) ?? ""}`,
```suggestion
              '2': `${procuraRotuloUf(usuario) ?? "-"}`,
```

2023-11-13 02:28 UTC, DanielPortods commented on src/pages/gerencia/GerenciarUsuario/index.tsx
> +              setAtualizaMunicipioSelecionado(`${usuario.municipio.id}`)
```suggestion
              setAtualizaMunicipioSelecionado(`${usuario.municipio?.id}`)
```

2023-11-13 11:19 UTC, RafaelBP02 commented
Lamego, com as sugestões do Daniel o tipo municipio aceita tipo indefinido. Agora não deve ter mais problema no docker e não mostra mais a mensagem de erro

2023-11-13 11:31 UTC, DanielPortods approved these changes

2023-11-13 17:41 UTC, VitorLamego approved these changes
Bom trabalho, pessoal !! Código segue o padrão esperado e as funcionalidades e melhorias acrescentadas estão respondendo bem.

2023-11-13 17:44 UTC, merged