US 3: Gerenciar empresas terceirizadas
fga-eps-mds/2023.2-Dnit-Front pull request #27
Opened 2023-11-19 14:04 UTC by wagnermc506

## _Issue :_ US 3: Gerenciar empresas terceirizadas

Resolves fga-eps-mds/2023.1-Dnit-Front#XX

 

## Descrição

Adiciona o CRUD de empresas e relação com os usuários, além do filtro de empresa na tabela de usuários
## Imagens:

## Tipo de alterações

- [ ] _correção_ _de_ _bug_
- [x] Nova _feature_
- [ ] Outro: 
## Lista de controle:

- [x] Atribui este pull request ao projeto
- [x] Meu código segue a folha de estilos implementada
- [x] Meus _commits_ seguem a política de commits do projeto.
- [ ] Minhas alterações requerem modificações na documentação atual.
- [ ] Atualizei a Documentação
- [x] Adicionei testes para cobrir minhas alterações.
- [ ] Todos os testes foram aprovados.

2023-11-19 14:20 UTC, RafaelBP02 submitted a review, later dismissed
A cobertura de testes está abaixo de 80%. O Sonar cloud precisa está aprovando isso

2023-11-19 14:20 UTC, RafaelBP02 commented on src/pages/info/Dashboard/index.tsx
> +          {}
Isso aqui faz nada
```suggestion
         
```

2023-11-19 14:45 UTC, RafaelBP02 commented
![image](https://github.com/fga-eps-mds/2023.2-Dnit-Front/assets/50378927/22955236-fdce-4d3e-839a-fca63e849f2f)
O dropdown da seleção de UF está com uma formatação muito esquisita

2023-11-19 14:58 UTC, RafaelBP02 commented
### Erro ao tentar apagar uma empresa

Tentei apagar uma empresa que tinha alocado em um usuário e deu esse erro:
![image](https://github.com/fga-eps-mds/2023.2-Dnit-Front/assets/50378927/52990c9a-f236-4052-826a-9fc45d4f94da)

As soluções que eu vejo são:
1. Mudar esse aviso para algo como: "Não foi possível apagar, existem usuários registrados nessa empresa";
2. Ou, Remover todos os usuarios dessa empresa automaticamente quando ela for apagada

2023-11-19 15:06 UTC, RafaelBP02 requested changes
Corrigir os bugs encontrados ao testar o front

2023-11-19 16:52 UTC, csreis72 commented
@RafaelBP02 Foi corrigido o estilo do seletor de UFs, conforme a imagem abaixo. No entanto, como esse seletor permite múltiplas opções, acredito que ele não deve fechar ao selecionar uma única UF.
<img width="375" alt="image" src="https://github.com/fga-eps-mds/2023.2-Dnit-Front/assets/112133277/3be80141-7f5e-4464-ac8c-c365d8b7695f">

2023-11-19 23:50 UTC, RafaelBP02 commented
Por favor, corriga os conflitos com a develop

2023-11-20 02:05 UTC, RafaelBP02 reviewed
Falta remover comentários

2023-11-20 02:05 UTC, RafaelBP02 commented on src/tests/components/AdicionarUsuarioDialog.spec.tsx
> +// import { Permissao } from "../models/auth";
Remover cometários desnecessários
```suggestion
// import { Permissao } from "../models/auth";
```

2023-11-20 02:07 UTC, wagnermc506 commented on src/tests/components/AdicionarUsuarioDialog.spec.tsx
> +// import { Permissao } from "../models/auth";
Comentários removidos

2023-11-20 02:08 UTC, RafaelBP02 approved these changes
Bom trabalho

2023-11-20 02:32 UTC, merged