Feat/74 custo logistico
fga-eps-mds/2023.2-Dnit-Front pull request #28
Opened 2023-11-19 19:54 UTC by victorhugo21

## _Issue :_ Nome da issue

Resolves fga-eps-mds/2023.1-Dnit-Front#XX

 

## Descrição

## Imagens:

## Tipo de alterações

- [ ] _correção_ _de_ _bug_
- [ ] Nova _feature_
- [ ] Outro: 
## Lista de controle:

- [ ] Atribui este pull request ao projeto
- [ ] Meu código segue a folha de estilos implementada
- [ ] Meus _commits_ seguem a política de commits do projeto.
- [ ] Minhas alterações requerem modificações na documentação atual.
- [ ] Atualizei a Documentação
- [ ] Adicionei testes para cobrir minhas alterações.
- [ ] Todos os testes foram aprovados.

2023-11-19 20:50 UTC, thiagohdaqw commented on src/models/service.ts
> +  if: number;
aqui é `if` mesmo? @victorhugo21

2023-11-19 21:06 UTC, thiagohdaqw commented
## Preview

A us6 tem o preview em: 'https://escola.dnit.eps-fga.live/us6' então dá pra testar sem precisar subir o backend localmente.
Configure o .env com:
```
REACT_APP_API_USUARIOS=https://usuario.dnit.eps-fga.live
REACT_APP_API_ESCOLAS=https://escola.dnit.eps-fga.live/us6
REACT_APP_API_UPS=https://up.dnit.eps-fga.live
```

2023-11-19 23:38 UTC, thiagohdaqw commented
## Preview

https://red-meadow-098bec310-preview.centralus.4.azurestaticapps.net

2023-11-19 23:47 UTC, RafaelBP02 commented
### Inconsistencia na apresentação de dados

![image](https://github.com/fga-eps-mds/2023.2-Dnit-Front/assets/50378927/4d837c5b-99c3-43aa-82cb-9a7c2ccc4fe8)

Os dados de superintendencia deveriam estar com quebra de linha

2023-11-19 23:47 UTC, VitorLamego commented on src/components/EscolaRanqueModal/index.tsx
> +                    <div>
A formatação em linhas das informações de superintendência não estão corretas.

![Captura de Tela 2023-11-19 às 20 47 16](https://github.com/fga-eps-mds/2023.2-Dnit-Front/assets/54643464/f9b75027-9c92-4544-ac9f-1bb61914a732)

2023-11-19 23:49 UTC, RafaelBP02 reviewed
Concertar as observações feitas

2023-11-19 23:49 UTC, VitorLamego commented on src/components/EscolaRanqueModal/index.tsx
> +                            <Label>Telefone: {escolaSelecionada.telefone}</Label>
Fiquei incomodado com a falta de formatação do número de telefone, sem os (##) ####-####, os números todos juntos ficaram estranhos para mim. Relacionado a isso, o CEP também poderia estar com a formatação correta, utilizando '.' e '-'

2023-11-19 23:57 UTC, VitorLamego commented on src/components/escolasCadastradas/modal/ModalCampos/index.tsx
O campo 'Situação' está abrindo um novo ícone de dropdown quando algum valor é selecionado, não sei se o bug já estava na aplicação, mas a usabilidade está bem ruim. Um outro comentário do ponto de vista pessoal é que o campo 'Observações' ficou muito pequeno para ser um input de text area, vi que isso já existia no código, mas é bom deixar mapeado como uma melhoria.


![Captura de Tela 2023-11-19 às 20 52 31](https://github.com/fga-eps-mds/2023.2-Dnit-Front/assets/54643464/6cccc2f6-b0fa-42e8-830e-66b5e6458e85)

2023-11-20 00:16 UTC, VitorLamego requested changes
Bom trabalho, não encontrei problemas no código, só deixei apontado algumas melhorias referente a usabilidade

2023-11-20 00:25 UTC, RafaelBP02 approved these changes
Bom trabalho!

2023-11-20 00:26 UTC, victorhugo21 commented on src/components/escolasCadastradas/modal/ModalCampos/index.tsx
Esses problema já havia e durante o desenvolvimento acabou não sendo mapeado, então fica de melhoria

2023-11-20 00:27 UTC, yudi-azvd approved these changes

2023-11-20 00:29 UTC, VitorLamego approved these changes
Bom trabalho!

2023-11-20 00:30 UTC, merged