Feat/85 gerenciar solitacao acao
fga-eps-mds/2023.2-Dnit-Front pull request #33
Opened 2023-12-01 22:48 UTC by RafaelBP02

## _Issue :_ US 7: Gerenciar solicitações de ações

Resolves fga-eps-mds/2023.1-Dnit-Front#85

 

## Descrição
Cria um novo fluxo para gerenciar solicitação de ação e adiciona nos detalhes das escolas do rank se possui uma solicitação ou não

## Observações:
Para testar essa US será necessário:
1. Subir o container de banco de dados
2. Subir localmente o serviço de escolas e UPS
3. Subir o front

## Tipo de alterações

- [ ] _correção_ _de_ _bug_
- [ ] Nova _feature_
- [ ] Outro: 
## Lista de controle:

- [ ] Atribui este pull request ao projeto
- [ ] Meu código segue a folha de estilos implementada
- [ ] Meus _commits_ seguem a política de commits do projeto.
- [ ] Minhas alterações requerem modificações na documentação atual.
- [ ] Atualizei a Documentação
- [ ] Adicionei testes para cobrir minhas alterações.
- [ ] Todos os testes foram aprovados.

2023-12-01 22:49 UTC, RafaelBP02 commented
Estou finalizando os testes da página de solicitações no dashboard

2023-12-04 01:31 UTC, thiagohdaqw requested changes
![image](https://github.com/fga-eps-mds/2023.2-Dnit-Front/assets/54081877/013ccd21-1bc3-47bd-82ee-5b0f3849515b)

bom trabalho galera, mas encontrei esse bug ai nos detalhes

2023-12-04 01:32 UTC, thiagohdaqw commented
Talvez seria interessante também autocompletar o código da escola na hora de criar a escola. Achei bem complicada essa experiencia de colocar o codigo manualmente, sendo que existe esse dado no backend

2023-12-04 01:33 UTC, thiagohdaqw commented
As permissões foram implementadas? Acho que seria interessante tambem ter uma permissao pra visualizar ação e, na hora de criar a escola, verificar se o usuariot em a permissao EscolaCadastrar

2023-12-04 02:44 UTC, thiagohdaqw approved these changes

2023-12-04 02:47 UTC, merged