Hotfix/37 refatorar a disposicao das pastas do front
fga-eps-mds/2023.2-Dnit-Front pull request #5
Opened 2023-10-17 20:06 UTC by bottinolucas

## _Issue :_ [#37](https://github.com/fga-eps-mds/2023.2-Dnit-DOC/issues/37)

## Descrição

As alterações realizadas neste Pull Request basearam-se numa melhor organização da disposição das pastas no front-end do projeto, em que cada pasta faz jus a um componente. Alterações em arquivos de estilização do projeto, disposição dos arquivos de estilização e visualização de cada componente estão presentes também neste Pull Request.
As pastas foram separadas para que o index.tsx fosse correspondido a um determinado componente.

## Imagens:
![image](https://github.com/fga-eps-mds/2023.2-Dnit-Front/assets/101297130/b2999965-777f-42b9-a107-2756e5cf4dd9)
![image](https://github.com/fga-eps-mds/2023.2-Dnit-Front/assets/101297130/06a94725-0147-41da-87c5-32df236a2069)
![image](https://github.com/fga-eps-mds/2023.2-Dnit-Front/assets/101297130/738dba1a-3c1b-46e1-bf28-d65eafb8d5d5)

## Tipo de alterações

- [ ] Alteração na pasta Components (Disposição de cada componente de acordo com sua funcionalidade e generalidade)
- [ ] Alteração na pasta Styles (Junção de arquivos mais gerais em arquivos mais específicos, além de especificar o caminho de cada estilização para seus respectivos alvos)
- [ ] Alteração na pasta Pages (Correção semelhante a pasta Components, em que a disposição foi realizada de acordo com sua funcionalidade e generalidade)

## Lista de controle:

- [ ] Atribui este pull request ao projeto
- [ ] Meu código segue a folha de estilos implementada
- [ ] Meus _commits_ seguem a política de commits do projeto.
- [ ] Todos os testes foram aprovados.

2023-10-24 16:04 UTC, RafaelBP02 requested changes
Será necessário fazer um rebase para adaptar os novos componentes de Header e Footer que não seguem esse padrão das pastas

2023-10-29 23:51 UTC, thiagohdaqw commented
> Será necessário fazer um rebase para adaptar os novos componentes de Header e Footer que não seguem esse padrão das pastas

*merge, rebase reescreve os commits

2023-11-05 00:29 UTC, victorhugo21 commented
Na hora de dar o merge, primeiro esse [PR](https://github.com/fga-eps-mds/2023.2-Dnit-Front/pull/20)

2023-11-08 00:39 UTC, VitorLamego requested changes
A disposição das pastas por mim está ok. Estourou um erro quando eu rodei o docker referente ao props sendo utilizado no Botao/styles.tsx, mas pelo o que eu me lembro esse componente deixou de ser utilizado para usar o novo botão criado seguindo o design system, então acredito que tenha que só atualizar essa questão dos novos componentes que entraram

2023-11-08 18:31 UTC, victorhugo21 commented
Acredito ter solucionado os problemas @VitorLamego, peço que confira. Obrigado!!

2023-11-09 02:43 UTC, RafaelBP02 reviewed
Não tive problemas ao rodar esse front. Só pedi para remover um comentário. Essa reorganização será muito bem vinda para o front

2023-11-09 02:43 UTC, RafaelBP02 commented on src/tests/CadastrarEscola.spec.tsx
> +  //await screen.findByText("Erro ao fazer o cadastro");
```suggestion

```
Remover esse comentário

2023-11-09 17:21 UTC, RafaelBP02 approved these changes

2023-11-10 22:40 UTC, merged